/*
 * generated by Xtext 2.12.0
 */
package work.worklang.scoping

import org.eclipse.emf.ecore.EReference
import org.eclipse.emf.ecore.EObject

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class WorkScopeProvider extends AbstractWorkScopeProvider {

	override getScope(EObject context, EReference reference){
		return super.getScope(context, reference)
	}

}
