/*
 * generated by Xtext 2.12.0
 */
package org.worklang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WorkStandaloneSetup extends WorkStandaloneSetupGenerated {

	def static void doSetup() {
		new WorkStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
