/*
 * generated by Xtext 2.12.0
 */
package org.worklang.generator


import io.vertx.core.Vertx
import org.worklang.interpreter.RESTVerticle

class Main {
	
	static Vertx vertx = Vertx.vertx(); 

	def static main(String[] args) {
		
		println("Initializing REST API")
		
		var RESTVerticle restapi = new RESTVerticle()
		
		println("Attempting to deploy REST API")
		 
		vertx.deployVerticle(restapi)

		
		return
	}

	
}
